steps:
  # Build the frontend container (uses nginx proxy for API requests)
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.prod'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-frontend:latest'
      - '.'

  # Push the frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-frontend:latest']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sdp-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-frontend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'

  # Build the admin frontend container
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.admin'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-admin:latest'
      - '.'

  # Push the admin frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-admin:latest']

  # Deploy admin frontend to Cloud Run (restricted access)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sdp-admin'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-admin:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'

  # Build the backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-backend:latest', '-f', 'Dockerfile.backend', '.']

  # Push the backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-backend:latest']

  # Run database migrations using Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Delete existing job if it exists (ignore error if it doesn't exist)
        gcloud run jobs delete sdp-migration --region=us-central1 --quiet || true

        # Create migration job (runs from /app/backend where alembic.ini is)
        gcloud run jobs create sdp-migration \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-backend:latest \
          --region=us-central1 \
          --command=sh \
          --args=-c,"cd /app/backend && alembic upgrade head" \
          --set-cloudsql-instances=$PROJECT_ID:us-central1:sdp-db-prod \
          --set-secrets=DATABASE_URL=database-url:latest \
          --max-retries=0

        # Execute the job
        gcloud run jobs execute sdp-migration --region=us-central1 --wait

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sdp-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--update-env-vars'
      - 'DEBUG=false,FRONTEND_URL=https://sdp-frontend-zziiwqh26q-uc.a.run.app,BACKEND_URL=https://sdp-backend-zziiwqh26q-uc.a.run.app'
      - '--update-secrets'
      - 'DATABASE_URL=database-url:latest,GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,JWT_SECRET_KEY=jwt-secret:latest,ANTHROPIC_API_KEY=anthropic-api-key:latest'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:sdp-db-prod'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-frontend:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-admin:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sdp-repo/sdp-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
